//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool
//     Changes to this file will be lost if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
namespace Application.Enterprise.CommonObjects
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel;
    using System.Linq;
    using System.Text;

    public class Transaction : INotifyPropertyChanged
	{
		public virtual int Id
		{
			get;
			set;
		}

		public virtual DateTime Date
		{
			get;
			set;
		}

		public virtual long Quantity
		{
			get;
			set;
		}

		public virtual double StockValue
		{
			get;
			set;
		}

		public virtual object PriceLeader
		{
			get;
			set;
		}

      

        private double _PurchasePrice;
        public double PurchasePrice
        {
            get { return _PurchasePrice; }
            set
            {
                _PurchasePrice = value;
                this.OnPropertyChanged("PurchasePrice");
            }
        }

        private double _SalePrice;
        public double SalePrice
        {
            get { return _SalePrice; }
            set
            {
                _SalePrice = value;
                this.OnPropertyChanged("SalePrice");
            }
        }


        

        public virtual double ClosingPrice
        {
            get;
            set;
        }

        private double _LastDayPrice;
        public virtual double LastDayPrice
        {
            get { return _LastDayPrice; }
            set
            {
                _LastDayPrice = value;
                this.OnPropertyChanged("LastDayPrice");
            }
        }

        private double _Minimum;
        public virtual double Minimum
		{
            get { return _Minimum; }
            set
            {
                _Minimum = value;
                this.OnPropertyChanged("Minimum");
            }
        }

        private double _Maximum;
        public virtual double Maximum
		{
            get { return _Maximum; }
            set
            {
                _Maximum = value;
                this.OnPropertyChanged("Maximum");
            }
        }


        public virtual double MinimumLimit
        {
            get;
            set;
        }

        public virtual double MaximumLimit
        {
            get;
            set;
        }


        private double _Average;
        public virtual double Average
		{
            get { return _Average; }
            set
            {
                _Average = value;
                this.OnPropertyChanged("Average");
            }
        }

        private double _Variation;
        public virtual double Variation
		{
            get { return _Variation; }
            set
            {
                _Variation = value;
                this.OnPropertyChanged("Variation");
            }
        }

        private double _TotalTrading;
        public virtual double TotalTrading
		{
            get { return _TotalTrading; }
            set
            {
                _TotalTrading = value;
                this.OnPropertyChanged("TotalTrading");
            }
        }


        public virtual Int64 OperationsNumber
        {
            get;
            set;
        }


		/*public virtual Instrument Instrument
		{
			get;
			set;
		}

        public virtual Issuer Issuer
        {
            get;
            set;
        }
        */
        public virtual string state
        {
            get;
            set;
        }

        public virtual DateTime xdividendperiod
        {
            get;
            set;
        }

        public virtual double DividendPerStock
        {
            get;
            set;
        }

        private double _TargetPrice;
        public double TargetPrice
        {
            get { return _TargetPrice; }
            set
            {
                _TargetPrice = value;
                this.OnPropertyChanged("TargetPrice");
            }
        }

        //----------------------------------------
        //TODO: Mauricio
        private double _TargetQuantity;
        public double TargetQuantity
        {
            get { return _TargetQuantity; }
            set
            {
                _TargetQuantity = value;
                this.OnPropertyChanged("TargetQuantity");
            }
        }


        private double _RangePriceMin;
        public double RangePriceMin
        {
            get { return _RangePriceMin; }
            set
            {
                _RangePriceMin = value;
                this.OnPropertyChanged("RangePriceMin");
            }
        }


        private double _RangePriceMax;
        public double RangePriceMax
        {
            get { return _RangePriceMax; }
            set
            {
                _RangePriceMax = value;
                this.OnPropertyChanged("RangePriceMax");
            }
        }


        private double _LimiteNegMin;
        public double LimiteNegMin
        {
            get { return _LimiteNegMin; }
            set
            {
                _LimiteNegMin = value;
                this.OnPropertyChanged("LimiteNegMin");
            }
        }


        private double _LimiteNegMax;
        public double LimiteNegMax
        {
            get { return _LimiteNegMax; }
            set
            {
                _LimiteNegMax = value;
                this.OnPropertyChanged("LimiteNegMax");
            }
        }

        //------------------------------------------------------
        private long _PurchaseQuantity;
        public virtual long PurchaseQuantity
        {
            get { return _PurchaseQuantity; }
            set
            {
                _PurchaseQuantity = value;
                this.OnPropertyChanged("PurchaseQuantity");
            }
        }

        private long _SaleQuantity;
        public virtual long SaleQuantity
        {
            get { return _SaleQuantity; }
            set
            {
                _SaleQuantity = value;
                this.OnPropertyChanged("SaleQuantity");
            }
        }

        private double _Open;
        public virtual double Open
        {
            get { return _Open; }
            set
            {
                _Open = value;
                this.OnPropertyChanged("Open");
            }
        }

        private string _SelectPrice;
        public virtual string SelectPrice
        {
            get { return _SelectPrice; }
            set
            {
                _SelectPrice = value;
                this.OnPropertyChanged("SelectPrice");
            }
        }

        private string _Auction;
        public virtual string Auction
        {
            get { return _Auction; }
            set
            {
                _Auction = value;
                this.OnPropertyChanged("Auction");
            }
        }

        private double _ReferencePrice;
        public virtual double ReferencePrice
        {
            get { return _ReferencePrice; }
            set
            {
                _ReferencePrice = value;
                this.OnPropertyChanged("ReferencePrice");
            }
        }

        public virtual string Error
        {
            get;
            set;
        }


        private bool _IsUpdate = false;
        public bool IsUpdate
        {
            get { return _IsUpdate; }
            set
            {
                _IsUpdate = value;
                this.OnPropertyChanged("IsUpdate");
            }
        }

        private int changeClosing = 0;
        public int ChangeClosing
        {
            get
            {
                return changeClosing;
            }
            set
            {
                if (value == ChangeClosing)
                {
                    return;
                }
                changeClosing = value;
                OnPropertyChanged("ChangeClosing");
            }
        }

        private double change;
        public double Change
        {
            get
            {

                return change;
                //if (ReferencePrice != 0)
                //{
                //    double val = (ReferencePrice * Variation) / 100;
                //    return Math.Round(val, 2);
                //}
                //else
                //    return 0;
            }
            set
            {
                if (value == Change)
                {
                    return;
                }
                change = value;
                OnPropertyChanged("Change");
            }
        }
        public event PropertyChangedEventHandler PropertyChanged;

        private void OnPropertyChanged(string propertyName)
        {
            PropertyChangedEventHandler handler = this.PropertyChanged;
            if (handler != null)
            {
                handler(this, new PropertyChangedEventArgs(propertyName));
            }
        }

        public virtual Int64 Consecutive
        {
            get;
            set;
        }

    }
}

